config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  root 'pages#index'
  get 'pages/index' => 'pages#index'
  get 'for-sponsors' => 'pages#for_sponsors'
  get 'for-speakers' => 'pages#for_speakers'

  resources :events, only: %i( show index )
  resources :offers, only: %i( show index )

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
end

app/models/admin_user.rb
# The model representing single admin user
class AdminUser < ApplicationRecord
  devise :database_authenticatable,
    :recoverable,
    :rememberable,
    :trackable,
    :validatable
end

app/models/application_record.rb
# A single point of entry for all the customizations and extensions needed for
# an activerecord model
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
# Model representing single meetup event
class Event < ApplicationRecord
  include Bootsy::Container

  enum status: { past: 0, upcoming: 1 }

  paginates_per 8

  scope :sorted, -> { order(time: :desc) }
end

app/models/offer.rb
# Model representing single sponsor's job offer
class Offer < ApplicationRecord
  belongs_to :sponsor

  scope :sorted, -> { order(created_at: :desc) }

  validates :title, presence: true
  validates :description, presence: true

  def to_param
    [id, sponsor&.name, title]
      .compact
      .join('-')
      .parameterize
  end
end

app/models/sponsor.rb
# Model representing single KRUG sponsor
class Sponsor < ApplicationRecord
  mount_uploader :logo, LogoUploader

  has_many :offers

  scope :sorted, -> { order(created_at: :desc) }

  validates :logo, presence: true
  validates :url, presence: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
# A single point of entry for all the customizations and extensions needed for
# an action controller
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :newest_meeting
  helper Bootsy::Engine.helpers

  private

  # Returns the newest events which we need in global scope
  def newest_meeting
    @newest_meeting = Event.sorted.first
  end
end

app/controllers/events_controller.rb
# Events controller
class EventsController < ApplicationController
  def index
    @events = events.page(params[:page])
  end

  def show
    @event = Event.find(params[:id])
    @previous_events = Event.where(id: previous_events_ids).reverse
  end

  private

  def events
    Events::IndexService.new.call
  end

  # Returns 3 previous events ids
  def previous_events_ids
    id = params[:id].to_i
    ((id - 3)..(id - 1))
  end
end

app/controllers/offers_controller.rb
# Offers controller
class OffersController < ApplicationController
  def index
    @offers = Offer.includes(:sponsor).sorted
  end

  def show
    @offer = Offer.find(params[:id])
  end
end

app/controllers/pages_controller.rb
# Controller responsible for rendering all static pages
class PagesController < ApplicationController
  # Setup and trigger landing page
  def index
    @sponsors = Sponsor.sorted
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(link_path)
    current_page?(link_path) ? 'active' : ''
  end

  def markdown(text)
    Redcarpet::Markdown.new(
      Redcarpet::Render::HTML,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      disable_indented_code_blocks: true,
      autolink: true,
      tables: true,
      underline: true,
      highlight: true
    ).render(text).html_safe
  end
end

app/helpers/offers_helper.rb
#  frozen_string_literal: true

module OffersHelper
  def offer_logo_url(offer)
    if offer.sponsor
      offer.sponsor.logo.thumb.url
    else
      LogoUploader.new.default_url
    end
  end
end

app/views/elements/_code_of_conduct.haml
%section#code-of-conduct
  .container
    .row.vertical-align
      .col-sm-6
        %h2.section-heading CODE OF CONDUCT

        %p
          %ul.lead
            %li
              Follow MINASWAN (Matz is Nice And So We Are Nice).
            %li
              Refrain from aggressive or intrusive HR practices.
            %li
              Alert community leaders, if you notice a dangerous situation or any violations of the following Code of Conduct.
            %li
              For details, go to Berlin Code of Conduct (http://berlincodeofconduct.org/).

      .col-sm-6
        .button-image.center-block
          = link_to 'READ MORE', 'http://berlincodeofconduct.org/', class: 'btn btn-primary center-block'

app/views/elements/_contact.html.haml
%section#contact
  .container
    .row.vertical-align
      .col-sm-5
        %h2.section-heading CONTACT
        %p.lead
          Would you like to share your concepts or dilemmas on one of our KRUG events? Or maybe you are up for sponsoring one of them? If your answer is yes to any of the two questions, drop us a message at
          = succeed '.' do
            = mail_to 'contact@krug.org.pl'

      .col-sm-7
        = render partial: 'elements/social'

app/views/elements/_footer.haml
= render partial: 'elements/contact'

%footer
  #location-map
  #ilu-bottom
  #copyright
    .container
      .row

app/views/elements/_header.haml
%header
  .pull-right
    = render partial: 'elements/social'
  #rubins
    .layer.layer-1
      = image_tag 'ruby.svg', class: 'rb1'
      = image_tag 'ruby.svg', class: 'rb2'
      = image_tag 'ruby.svg', class: 'rb3'
      = image_tag 'ruby.svg', class: 'rb4'
    .layer.layer-2
      = image_tag 'ruby.svg', class: 'rb1'
      = image_tag 'ruby.svg', class: 'rb2'
      = image_tag 'ruby.svg', class: 'rb3'
      = image_tag 'ruby.svg', class: 'rb4'
    .layer.layer-3
      = image_tag 'ruby.svg', class: 'rb1'
      = image_tag 'ruby.svg', class: 'rb2'
  .container
    .row
      .col-xs-12
        = image_tag 'logo_krug.svg', class: 'logo center-block'
    .row
      .col-xs-12
        = render partial: 'elements/navbar'

app/views/elements/_navbar.haml
%nav.navbar.navbar-default{ role: 'navigation' }
  %ul.nav.navbar-nav
    %li{ class: active_class(root_path) }
      = link_to 'HOME', root_path, class: 'lead'
    %li{ class: active_class(events_path) }
      = link_to 'MEETING ARCHIVE', events_path, class: 'lead'
    %li{ class: active_class(for_speakers_path) }
      = link_to 'FOR SPEAKERS', for_speakers_path, class: 'lead'
    %li{ class: active_class(offers_path) }
      = link_to 'JOB OFFERS', offers_path, class: 'lead'
    %li{ class: active_class(for_sponsors_path) }
      = link_to 'SPONSOR US', for_sponsors_path, class: 'lead'

app/views/elements/_newest_meeting.haml
%section#newest_meeting
  .container
    .row.vertical-align
      .col-sm-6
        %h2.section-heading= @newest_meeting.time.past? ? 'LAST MEETING' : 'NEXT MEETING'
        %p.lead #{@newest_meeting.time.strftime('%d.%m.%Y')} @ #{@newest_meeting.venue}
        %p.lead= @newest_meeting.name
      .col-sm-6.text-center
        .button-image.center-block
          = link_to 'READ MORE', event_path(@newest_meeting), class: 'btn btn-primary'
          = link_to 'MEETUP LINK', @newest_meeting.link, class: 'meetup-link'

app/views/elements/_social.haml
.social-list
  %ul.list-inline.center-block.text-center
    %li
      = link_to 'https://www.facebook.com/KrakowRubyUsersGroup/', target: '_blank', class: 'grow-rotate' do
        = image_tag 'ico_fb.svg', class: 'social-icon'
    %li
      = link_to 'http://www.meetup.com/Krakow-Ruby-Users-Group/', target: '_blank', class: 'grow-rotate' do
        = image_tag 'ico_mu.svg', class: 'social-icon'
    %li
      = link_to 'https://github.com/Krakow-Ruby-Users-Group/', target: '_blank', class: 'grow-rotate' do
        = image_tag 'ico_gh.svg', class: 'social-icon'
    %li
      = link_to 'http://crossweb.pl/cykle-wydarzen/krakow-ruby-users-group/', target: '_blank', class: 'grow-rotate' do
        = image_tag 'ico_cw.svg', class: 'social-icon'
    %li
      = mail_to 'contact@krug.org.pl', class: 'grow-rotate' do
        = image_tag 'ico_mail.svg', class: 'social-icon'

app/views/elements/_sponsors_list.haml
%section#sponsors
  .container
    .row
      .col-lg-12.text-left
        %h2.section-heading SPONSORS
      .row
        .sponsors-list
          - @sponsors.each do |sponsor|
            .col-xs-12.col-sm-6.col-md-3.offer-card.grow
              .logo.col-xs-12
                = link_to sponsor.url, target: '_blank' do
                  = image_tag sponsor.logo.thumb.url, class: 'center-block'
          .col-xs-12.col-sm-6.col-md-3.offer-card.grow
            .sponsor-us.logo.col-xs-12
              = link_to 'SPONSOR US', for_sponsors_path, class: 'btn btn-primary'

app/views/events/index.haml
%section#event-index
  .container
    .row
      .col-lg-12
        %ul.timeline
          - @events.each_with_index do |event, index|
            %li{ class: ('timeline-inverted' if index.even?) }
              .timeline-node
              .timeline-panel
                .timeline-heading
                  %h4= event.time.strftime('%d.%m.%Y, %I:%M %p')
                  %h4.subheading= event.name
                .timeline-body
                  %h4= link_to 'read more', event_path(event)

    .row
      .col-xs-offset-1.col-xs-10.col-sm-offset-4.col-sm-4
        = paginate @events

app/views/events/index.html.haml
.page-header
%table.table.table-striped
  %thead
    %tr
      %th ID
      %th name
      %th status
  %tbody
    - @events.each do |event|
      %tr
        %td= event.id
        %td= link_to event.name, event_path(event)
        %td= event.status

app/views/events/show.haml
%section#event-show
  .container
    .row
      .col-md-8
        %h2.section-heading= @event.name
        .small= @event.time.strftime('%d.%m.%Y')
        .small= @event.venue
        .meetup-description
          = @event.description&.html_safe
      .col-md-4
        %h2.section-heading OTHER MEETINGS
        - @previous_events.each do |event|
          .other-meetups.col-md-8.col-offset-4
            = link_to event.name, event_path(event)

app/views/events/show.html.haml
= @event.description&.html_safe

app/views/layouts/application.haml
!!!
%html
  %head
    = favicon_link_tag 'favicon.png'
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }
    %title Krakow Ruby Users Group (KRUG) (Kraków)
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{ content: 'width=device-width, initial-scale=1', name: 'viewport' }
  %body
    = render partial: 'elements/header'
    = bootstrap_flash
    = render partial: 'elements/newest_meeting' if @newest_meeting
    = yield
    = render partial: 'elements/footer'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }
    %title KRUG
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{ content: 'width=device-width, initial-scale=1', name: 'viewport' }
  %body
    = render partial: 'elements/navbar'
    = bootstrap_flash
    = yield

app/views/offers/index.haml
%section#offer-index
  .container
    .row
      .offer-list
        - @offers.each_with_index do |offer|
          .col-xs-12.col-sm-6.col-md-4.offer-card.grow
            = link_to offer_path(offer) do
              .logo.col-xs-12
                = image_tag offer_logo_url(offer), class: 'img-responsive center-block'

              .text-center
                %h4.section-heading= offer.title.upcase

        .col-xs-12.col-sm-6.col-md-4.offer-card.grow
          = link_to for_sponsors_path do
            .logo.col-xs-12
              %h2.section-heading.krug-red YOUR COMPANY HERE?
            .text-center
              %h4.section-heading.krug-red BECOME OUR SPONSOR

app/views/offers/show.haml
%section#offer-show
  .container
    .row
      .col-md-10
        %h2.section-heading= @offer.title
        .meetup-description
          = markdown(@offer.description)

app/views/pages/for_speakers.haml
%section#for-speakers
  .container
    .row
      .col-xs-12
        %h2.section-heading For speakers

        %p.lead
          If you are interested in having a presentation at KRUG meetup, please send your application via email at
          = succeed '.' do
            %a{ href: 'mailto:contact@krug.org.pl' }<
              contact@krug.org.pl

    .row
      .col-xs-12
        %ul.ruby-list
          %li
            When you prepare your presentation, be ready to deliver it in the 20 to 45 minutes timeframe (except of lightning talks).
          %li
            Make sure it shows how much is left; you can use a progress bar to illustrate it.
          %li
            The submission deadline for the subject is 14 days before the event.
          %li
            You can prepare and deliver your presentation either in Polish or English.
          %li
            The subject is approved by the ogranizers up to 3 days from submission.
          %li
            You  are entitled to 1 commercial/advertising slide at the maximum (except of Sponsor).
          %li
            You are entitled to vestigal advertising during the presentation. Maximum 1 slide and 30 seconds speech. (It does not apply to the sponsor)

= render partial: 'elements/code_of_conduct'

app/views/pages/for_speakers.html.haml
pages#for_speakers

app/views/pages/for_sponsors.haml
%section#for-sponsors
  .container
    .row
      .col-xs-12
        %h2.section-heading For sponsors

        %p.lead
          If you are interested in sponsoring KRUG, please send your offer via email at
          = succeed '.' do
            %a{ href: 'mailto:contact@krug.org.pl' }<
              contact@krug.org.pl

    .row
      .col-xs-12
        %ul.ruby-list
          %li
            Make sure to include basic details of your company (name, profile, short description).
          %li
            Your offer is a subject to organizers' decisions.
          %li
            If it is accepted, it does not always mean, you are the sponsor of the upcoming event.
          %li
            We usually select our sponsor 1-3 months ahead.
          %li
            We will inform you about the available dates and options with due notice.
          %li
            As a sponsor, you have right to disseminate advertising gadgets during the KRUG event (stickers, mugs etc.).
          %li
            The aforementioned materials can be displayed only in the place designated by organizers.
          %li
            Costs that you commit to bear can differ by 15% as to what is agreed.
          %li
            If your withdraw your sponsorship after it is agreed, it means you will not be allowed to sponsor KRUG again.
          %li
            If your sponsorship gets approval, you will be informed about the event date 7 days before its official announcement.
          %li
            You are allowed to request moving the event by one week, if it collides with your other activities.
          %li
            You are obliged to send a representative to the KRUG event in person.
          %li
            You are entitled to designate 10 people from your company to take part in the event independent of the tickets availability.

= render partial: 'elements/code_of_conduct'

app/views/pages/for_sponsors.html.haml
pages#for_sponsors

app/views/pages/index.haml
#homepage
  %section#rules
    .container
      .row
        .col-xs-12.col-md-4
          = link_to 'http://berlincodeofconduct.org/', class: 'grow center-block' do
            = image_tag 'ilu_attendees.svg', class: 'img-responsive center-block'
            .caption.text-center
              %h3 Rules for attendees

        .col-xs-12.col-md-4
          = link_to for_speakers_url, class: 'grow center-block' do
            = image_tag 'ilu_lecturers.svg', class: 'img-responsive center-block'
            .caption.text-center
              %h3 Rules for speakers

        .col-xs-12.col-md-4
          = link_to for_sponsors_url, class: 'grow center-block' do
            = image_tag 'ilu_sponsoring.svg', class: 'img-responsive center-block'
            .caption.text-center
              %h3 Rules for sponsors
  = render partial: 'elements/sponsors_list'

= render partial: 'elements/code_of_conduct'

app/views/pages/index.html.haml
%h1 Landings#index
%p Find me in app/views/landings/index.html.erb